# These are supported funding model platforms

github: [yousoftme]
patreon: yousoftme
open_collective: yousoftme
ko_fi: yousoftme
tidelift: npm/yousoftme
community_bridge: w3learnings
liberapay: yousoftme
issuehunt: yousoftme
otechie: yousoftme
custom: ['https://w3learnings.com']